const Constants = {
  SIZE: 9,
  BOX: 3,
  DIGITS: [1, 2, 3, 4, 5, 6, 7, 8, 9],
  START_SCORE: 120,
  FAIL_THRESHOLD: 30,
  WRONG_PENALTY: 15,
  HINT_PENALTY: 8,
  URL_VERSION: "3",
  EXPORT_VERSION: "sudoku-party-export-v1",
  SCORE_KEY: "sudoku-party-scores-v3",
  DAILY_SCORE_KEY: "sudoku-party-daily-v1",
  SETTINGS_KEY: "sudoku-party-settings-v1",
};

const DIFFICULTIES = {
  easy: { holes: 38, target: 20 },
  medium: { holes: 46, target: 55 },
  hard: { holes: 54, target: 110 },
};

const I18N = {
  zh: {
    "app.title": "数独派对 Pro",
    "mode.normal": "普通",
    "mode.daily": "每日挑战",
    "label.mode": "模式：{mode}",
    "label.day": "日期：{day}",
    "label.timer": "计时：{time}",
    "label.score": "得分：{score}",
    "label.filled": "已填：{filled}/81",
    "label.best.none": "最佳：--:--",
    "label.best": "最佳：{time} ｜ {score}分",
    "label.failThreshold": "失败阈值：{n}",
    "label.meta": "难度：{diff} ｜ Seed: {seed}",
    "leaderboard.normal": "本地排行榜（前 5）",
    "leaderboard.daily": "今日排行榜（{day}，前 5）",
    "leaderboard.empty.normal": "还没有成绩，快冲一把。",
    "leaderboard.empty.daily": "今天还没有成绩。",
    "btn.note": "笔记模式",
    "btn.undo": "撤销",
    "btn.redo": "重做",
    "btn.erase": "擦除",
    "btn.hint": "提示",
    "btn.newGame": "新布局",
    "btn.share": "分享进度",
    "btn.settings": "设置",
    "btn.copyDaily": "复制今日链接",
    "btn.autoCandidates": "自动候选",
    "btn.clearCandidates": "清空候选",
    "btn.mute": "静音",
    "btn.contrast": "高对比",
    "btn.font": "大字号",
    "btn.effect.low": "特效低",
    "btn.effect.medium": "特效中",
    "btn.effect.high": "特效高",
    "btn.export": "导出数据",
    "btn.import": "导入数据",
    "btn.retry": "再来一局",
    "btn.close": "关闭",
    "settings.title": "设置",
    "label.volume": "音量",
    "diff.easy": "简单",
    "diff.medium": "中等",
    "diff.hard": "困难",
    "status.failed": "分数跌破阈值，本局失败。",
    "status.start": "点击一个空格开始。",
    "status.noteMode": "笔记模式已开启，点击空格后输入数字。",
    "status.fixed": "这是预设数字，不能修改。",
    "status.pos": "第 {r} 行，第 {c} 列{mode}",
    "status.pos.noteSuffix": "（笔记模式）",
    "status.failWithAction": "分数跌破阈值，本局失败。点“再来一局”继续。",
    "toast.fail": "游戏失败：扣分过多。",
    "toast.autoCandidates.updated": "已自动补全候选（{n}格更新）",
    "toast.autoCandidates.latest": "候选已是最新",
    "toast.clearCandidates": "已清空所有候选。",
    "toast.restore": "已恢复你分享的进度。",
    "toast.newPuzzle": "布局已生成，祝你玩得开心！",
    "toast.noteUpdated": "候选数已更新。",
    "toast.wrong": "填写错误，已扣分",
    "toast.correct": "填写正确。",
    "toast.erased": "已擦除该格。",
    "toast.noHint": "没有可提示的格子。",
    "toast.hintUsed": "使用提示，已扣分",
    "toast.noUndo": "没有可撤销的操作。",
    "toast.undo": "已撤销一步。",
    "toast.noRedo": "没有可重做的操作（先撤销一步）。",
    "toast.redo": "已重做一步。",
    "toast.export.ok": "数据已导出。",
    "toast.export.fail": "导出失败。",
    "toast.import.badVersion": "导入失败：版本不兼容。",
    "toast.import.ok": "数据导入成功。",
    "toast.import.fail": "导入失败：文件内容无效。",
    "toast.share.system": "已调用系统分享。",
    "toast.share.copied": "进度链接已复制到剪贴板。",
    "toast.share.fail": "分享失败，可直接复制地址栏链接。",
    "toast.daily.copied": "今日挑战链接已复制。",
    "toast.daily.copyFail": "复制失败。",
    "toast.longPressNew": "已长按快速新开。",
    "toast.mute.on": "已静音。",
    "toast.mute.off": "已取消静音。",
    "toast.contrast.on": "已开启高对比。",
    "toast.contrast.off": "已关闭高对比。",
    "toast.font.on": "已开启大字号。",
    "toast.font.off": "已关闭大字号。",
    "toast.effect": "特效强度：{name}",
    "effect.low": "低",
    "effect.medium": "中",
    "effect.high": "高",
    "confirm.new.desktop": "当前对局尚未完成，确认开新局？",
    "confirm.new.mobile": "短按会二次确认，长按可直接新开。确认现在新开吗？",
    "share.text": "来玩我这盘数独（含当前进度）：{url}",
    "share.title": "数独派对 Pro",
    "share.invite": "这盘布局挺有意思，来试试！",
    "aria.fixed": "固定",
    "aria.editable": "可编辑",
    "aria.candidates": "候选 {value}",
    "aria.empty": "空",
    "aria.cell": "第 {r} 行第 {c} 列，{fixed}，当前 {value}",
    "title.win": "恭喜通关",
    "title.fail": "本局失败",
    "result.winReason": "你完成了本局数独。",
    "result.failReason": "扣分达到失败阈值。",
    "result.mode": "模式：{mode}",
    "result.mode.daily": "每日挑战 {day}",
    "result.mode.normal": "普通",
    "result.diff": "难度：{diff}",
    "result.time": "用时：{time}",
    "result.score": "得分：{score}",
    "result.wrong": "错误次数：{n}",
    "result.hint": "提示次数：{n}",
    "result.candidate": "候选使用次数：{n}",
    "result.rating": "难度评分：{score}（裸单元 {naked} / 隐单元 {hidden} / 区块摒除 {locked}）",
    "result.dailyRank": "今日排名（本地）：#{n}",
  },
  en: {
    "app.title": "Sudoku Party Pro",
    "mode.normal": "Normal",
    "mode.daily": "Daily",
    "label.mode": "Mode: {mode}",
    "label.day": "Day: {day}",
    "label.timer": "Time: {time}",
    "label.score": "Score: {score}",
    "label.filled": "Filled: {filled}/81",
    "label.best.none": "Best: --:--",
    "label.best": "Best: {time} | {score} pts",
    "label.failThreshold": "Fail Threshold: {n}",
    "label.meta": "Difficulty: {diff} | Seed: {seed}",
    "leaderboard.normal": "Local Leaderboard (Top 5)",
    "leaderboard.daily": "Today's Leaderboard ({day}, Top 5)",
    "leaderboard.empty.normal": "No records yet. Be the first!",
    "leaderboard.empty.daily": "No scores yet today.",
    "btn.note": "Notes",
    "btn.undo": "Undo",
    "btn.redo": "Redo",
    "btn.erase": "Erase",
    "btn.hint": "Hint",
    "btn.newGame": "New Board",
    "btn.share": "Share Progress",
    "btn.settings": "Settings",
    "btn.copyDaily": "Copy Daily Link",
    "btn.autoCandidates": "Auto Candidates",
    "btn.clearCandidates": "Clear Candidates",
    "btn.mute": "Mute",
    "btn.contrast": "High Contrast",
    "btn.font": "Large Font",
    "btn.effect.low": "FX Low",
    "btn.effect.medium": "FX Medium",
    "btn.effect.high": "FX High",
    "btn.export": "Export Data",
    "btn.import": "Import Data",
    "btn.retry": "Play Again",
    "btn.close": "Close",
    "settings.title": "Settings",
    "label.volume": "Volume",
    "diff.easy": "Easy",
    "diff.medium": "Medium",
    "diff.hard": "Hard",
    "status.failed": "Score dropped below threshold. Game over.",
    "status.start": "Tap a cell to start.",
    "status.noteMode": "Notes mode is on. Select a cell and enter digits.",
    "status.fixed": "This is a fixed clue and cannot be edited.",
    "status.pos": "Row {r}, Col {c}{mode}",
    "status.pos.noteSuffix": " (notes mode)",
    "status.failWithAction": "Score dropped below threshold. Tap Play Again.",
    "toast.fail": "Game over: too many penalties.",
    "toast.autoCandidates.updated": "Auto candidates updated ({n} cells).",
    "toast.autoCandidates.latest": "Candidates are already up to date.",
    "toast.clearCandidates": "All candidates cleared.",
    "toast.restore": "Shared progress restored.",
    "toast.newPuzzle": "New puzzle is ready. Have fun!",
    "toast.noteUpdated": "Candidates updated.",
    "toast.wrong": "Wrong input, penalty applied",
    "toast.correct": "Correct input.",
    "toast.erased": "Cell erased.",
    "toast.noHint": "No hint available.",
    "toast.hintUsed": "Hint used, penalty applied",
    "toast.noUndo": "Nothing to undo.",
    "toast.undo": "Undo applied.",
    "toast.noRedo": "Nothing to redo (undo first).",
    "toast.redo": "Redo applied.",
    "toast.export.ok": "Data exported.",
    "toast.export.fail": "Export failed.",
    "toast.import.badVersion": "Import failed: incompatible version.",
    "toast.import.ok": "Data imported.",
    "toast.import.fail": "Import failed: invalid file.",
    "toast.share.system": "System share opened.",
    "toast.share.copied": "Progress link copied.",
    "toast.share.fail": "Share failed. Copy URL manually.",
    "toast.daily.copied": "Daily challenge link copied.",
    "toast.daily.copyFail": "Copy failed.",
    "toast.longPressNew": "Quick new board by long press.",
    "toast.mute.on": "Muted.",
    "toast.mute.off": "Unmuted.",
    "toast.contrast.on": "High contrast on.",
    "toast.contrast.off": "High contrast off.",
    "toast.font.on": "Large font on.",
    "toast.font.off": "Large font off.",
    "toast.effect": "Effect intensity: {name}",
    "effect.low": "Low",
    "effect.medium": "Medium",
    "effect.high": "High",
    "confirm.new.desktop": "Current game is not finished. Start a new board?",
    "confirm.new.mobile": "Tap asks confirmation; long press starts immediately. Start now?",
    "share.text": "Try my Sudoku board (with progress): {url}",
    "share.title": "Sudoku Party Pro",
    "share.invite": "This board is fun, give it a try!",
    "aria.fixed": "fixed",
    "aria.editable": "editable",
    "aria.candidates": "candidates {value}",
    "aria.empty": "empty",
    "aria.cell": "Row {r}, column {c}, {fixed}, current {value}",
    "title.win": "You Win",
    "title.fail": "Game Over",
    "result.winReason": "You solved this Sudoku board.",
    "result.failReason": "Penalty reached the fail threshold.",
    "result.mode": "Mode: {mode}",
    "result.mode.daily": "Daily {day}",
    "result.mode.normal": "Normal",
    "result.diff": "Difficulty: {diff}",
    "result.time": "Time: {time}",
    "result.score": "Score: {score}",
    "result.wrong": "Wrong entries: {n}",
    "result.hint": "Hints used: {n}",
    "result.candidate": "Candidate uses: {n}",
    "result.rating": "Difficulty score: {score} (Naked {naked} / Hidden {hidden} / Locked {locked})",
    "result.dailyRank": "Today's local rank: #{n}",
  },
};

export { Constants, DIFFICULTIES, I18N };
